#!/bin/bash
# Generate app icons for macOS and Windows from a source PNG

SOURCE_PNG="electron/icons/icon.png"
ICONSET_DIR="electron/icons/icon.iconset"

# Check if source exists
if [ ! -f "$SOURCE_PNG" ]; then
    echo "Error: Source PNG not found at $SOURCE_PNG"
    exit 1
fi

# Create iconset directory
mkdir -p "$ICONSET_DIR"

# Generate various sizes for macOS iconset
echo "Generating macOS icon sizes..."
sips -z 16 16     "$SOURCE_PNG" --out "$ICONSET_DIR/icon_16x16.png"
sips -z 32 32     "$SOURCE_PNG" --out "$ICONSET_DIR/icon_16x16@2x.png"
sips -z 32 32     "$SOURCE_PNG" --out "$ICONSET_DIR/icon_32x32.png"
sips -z 64 64     "$SOURCE_PNG" --out "$ICONSET_DIR/icon_32x32@2x.png"
sips -z 128 128   "$SOURCE_PNG" --out "$ICONSET_DIR/icon_128x128.png"
sips -z 256 256   "$SOURCE_PNG" --out "$ICONSET_DIR/icon_128x128@2x.png"
sips -z 256 256   "$SOURCE_PNG" --out "$ICONSET_DIR/icon_256x256.png"
sips -z 512 512   "$SOURCE_PNG" --out "$ICONSET_DIR/icon_256x256@2x.png"
sips -z 512 512   "$SOURCE_PNG" --out "$ICONSET_DIR/icon_512x512.png"
sips -z 1024 1024 "$SOURCE_PNG" --out "$ICONSET_DIR/icon_512x512@2x.png"

# Convert iconset to icns
echo "Creating .icns file..."
iconutil -c icns "$ICONSET_DIR" -o "electron/icons/icon.icns"

# Clean up iconset directory
rm -rf "$ICONSET_DIR"

echo "✅ macOS icon created: electron/icons/icon.icns"

# For Windows .ico, electron-builder can convert from PNG automatically
# But if you have ImageMagick installed, you can create it:
if command -v convert &> /dev/null; then
    echo "Creating Windows .ico file..."
    convert "$SOURCE_PNG" -define icon:auto-resize=256,128,64,48,32,16 "electron/icons/icon.ico"
    echo "✅ Windows icon created: electron/icons/icon.ico"
else
    echo "⚠️  ImageMagick not found. Windows .ico will be generated by electron-builder from PNG."
    # Copy PNG as fallback - electron-builder will convert it
    cp "$SOURCE_PNG" "electron/icons/icon.ico.png"
fi

echo ""
echo "Done! Icons are ready in electron/icons/"




